- hosts: node001
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
        username: root
  tasks:
  - name: Install httpd on CentOS 7
    yum:
     name: httpd
     state: latest
    notify:
    - start apache
  handlers:
  - name: start apache
    service:
     name: httpd
     state: restarted
